kotlin.code.style=official

#systemProp.http.proxyHost=mirrors.tencent.com
#systemProp.https.proxyHost=mirrors.tencent.com

#systemProp.http.backup.proxyHost=mirrors.aliyun.com
#systemProp.https.backup.proxyHost=mirrors.aliyun.com


org.gradle.parallel=true
# Recommend: your cpu cores * 1.5
org.gradle.workers.max=18

# Avoidance compiling and caching
org.gradle.caching=true
org.gradle.compile.avoidance=true

# Disable foojay toolchain auto checking
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false

# Disable bytecode improvement
# TODO：Gradle 8.8 has some questions between JDK21
org.gradle.internal.instrumentation.enabled=false


