kotlin.code.style=official

#systemProp.http.proxyHost=mirrors.tencent.com
#systemProp.https.proxyHost=mirrors.tencent.com

#systemProp.http.backup.proxyHost=mirrors.aliyun.com
#systemProp.https.backup.proxyHost=mirrors.aliyun.com


org.gradle.parallel=true
# Recommend: your cpu cores * 1.5
org.gradle.workers.max=18

# Avoidance compiling and caching
org.gradle.caching=true
org.gradle.compile.avoidance=true



